---
editor_options: 
  chunk_output_type: console
---

# Preparing vegetation data for GLMs

Here, we prepare the vegetation data to run GLMs in the next series of scripts. 

Install required libraries
```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(vegan)
library(ggplot2)
library(scico)
library(psych)

# Source any custom/other internal functions necessary for analysis
source("code/01_internal-functions.R")
```


Load the vegetation data
```{r}
veg <- read.csv("data/2020-vegetation-data.csv")
veg$Site_ID <- str_remove(veg$Site_ID,"_")

# We load the subset data
datSubset <- read.csv("data/datSubset.csv")
sites_needed <- data.frame(unique(datSubset$Site))
names(sites_needed) <- "Site_ID"

# Obtain a subset of the data which have the sites visited 
veg <- merge(veg, sites_needed, by.x = "Site_ID", by.y="Site_ID")

# renaming restoration type
veg$Site_type[veg$Site_type=="Unrestored"] <- "Passive"
veg$Site_type[trial$Site_type=="Restored"] <- "Active"

# Load species-trait data to essentially run GLMs
trait_dat <- read.csv("data/species-trait-dat.csv")
```


Carrying out exploratory analysis and preparing a dataframe for further steps
```{r}
# Counting number of tree species and unique species per plot
treerich <- veg %>% 
  group_by(Site_ID) %>% 
  summarise (count = n(), richness = n_distinct(tree_species))

# Calculate average tree height across each unique site
treeheight <- veg %>% 
  drop_na(height) %>% 
  group_by(Site_ID) %>% 
  summarise(height = mean(height))

# Calculate basal area and left join with other data
basal_area <- veg %>% 
  mutate(basal_sum = rowSums(veg[,c(5:15)]^2)/(4*pi)) %>% group_by(Site_ID, Site_type) %>% 
  summarise(basal_area = sum(basal_sum)) 

# Calculate average canopy height
canopy_height <- veg %>%
  group_by(Site_ID) %>%
  summarise(canopy_cover = mean(Canopy_cover))

# Calculate average leaf litter
leaf_litter <- veg %>%
  group_by(Site_ID) %>%
  summarise(leaf_litter = mean(Leaf_litter))

# Calculate average vertical stratification
vert_strat <- veg %>%
  group_by(Site_ID) %>%
  summarise(vert_strat = mean(Foliage_score))

# Creating a final dataframe for further analysis
all_veg <- basal_area %>% 
  left_join(treeheight) %>%
  left_join(treerich) %>%
  left_join(canopy_height) %>%
  left_join(leaf_litter) %>%
  left_join(vert_strat)
```


Running a PCA of the vegetation data
```{r}
# Check for correlations among vegetation predictors
pairs.panels(all_veg[,3:9])

# The above panel suggests that richness is highly correlated with a number of predictors including canopy cover, count and basal area. We will calculate a PCA and keep the top two explanatory axes

veg_pca <- prcomp(all_veg[, 3:9], scale=TRUE, center = TRUE, retx=TRUE)
summary(veg_pca)

# The proportion of variance explained by the first two axes account for ~72.67%

# Plotting the first two axes
plot_data <- data.frame('Site_type' = all_veg$Site_type, veg_pca$x[,1:2]) # the first two components are selected 
pca_plot <- ggplot(data = plot_data) + 
       geom_point(aes(x = PC1, y = PC2, col = Site_type), size=2) + 
  scale_color_manual(values = scico(3, begin = 0.3, palette = "vik")) + theme_bw()
```


