---
editor_options: 
  chunk_output_type: console
---

# Generalized linear models and Mantel's tests

Install required libraries
```{r}
library(tidyverse)
library(dplyr)
library(stringr)
library(vegan)
library(ggplot2)
library(scico)
library(psych)

# Source any custom/other internal functions necessary for analysis
source("code/01_internal-functions.R")
```


Load the necessary data for statistical modeling
```{r}
# We load the subset data
datSubset <- read.csv("data/datSubset.csv")

# Load species-trait data to essentially check for associations by habitat type
trait_dat <- read.csv("data/species-trait-dat.csv")

# Total number of detections
totalDetections <- datSubset %>%
  group_by(Site, Restoration.Type) %>%
  transform() %>% replace(is.na(.), 0) %>%
  summarise_at(.vars = vars(c("IP":"CR")),.funs = sum) %>%
  summarise(totalDetections = sum(c_across("IP":"CR")))

# richness
richness <- datSubset %>%
  group_by(Site, Restoration.Type) %>%
  transform() %>% replace(is.na(.), 0) %>%
  summarise_at(.vars = vars(c("IP":"CR")),.funs = sum) %>% 
  mutate_at(vars(c("IP":"CR")),~ replace(., . > 0, 1)) %>%
  rowwise() %>% 
  mutate(richness = sum(c_across(IP:CR))) %>%
  dplyr::select(Site, Restoration.Type, richness)

# richness by Visit
# this data basically gives you richness per visit and adds a visit number for each consecutive visit to that site
richnessPerVisit <- datSubset %>%
  group_by(Site, Date, Restoration.Type) %>%
  transform() %>% replace(is.na(.), 0) %>%
  summarise_at(.vars = vars(c("IP":"CR")),.funs = sum) %>% 
  mutate_at(vars(c("IP":"CR")),~ replace(., . > 0, 1)) %>%
  rowwise() %>% 
  mutate(richness = sum(c_across(IP:CR))) %>%
  group_by(Site) %>% 
  mutate(visit = row_number()) %>%
  mutate(siteCode = str_extract(Site, pattern = "\\w+\\d+")) %>%
  mutate(siteCode = factor(siteCode)) %>%
  dplyr::select(Site, Restoration.Type, Date, richness, visit, siteCode)

# We further estimate the number of detections per point count
datSummary <- totalDetections %>%
  left_join(richness) %>%
  mutate(pointDetections = totalDetections/3)

# combine the Detections dataframe with the trait dataset
nDetectionsTrait <- datSubset %>%
  group_by(Site, Restoration.Type, Date) %>%
  transform() %>% replace(is.na(.), 0) %>%
  summarise_at(.vars = vars(c("IP":"CR")),.funs = sum) %>%
  pivot_longer(cols=IP:CR, names_to="Species_Code", values_to="count") %>%
  left_join(.,trait_dat, by=c("Species_Code"="species_annotation_codes")) %>%
  mutate(forRichness = case_when(count>0 ~ 1,count==0 ~ 0)) %>%
  rename(., nDetections = count)

# Load data from previous scripts for use in a GLM
vegData <-  read.csv("data/summaryVeg.csv")
vegPcaScores <- read.csv("data/pcaVeg.csv")
jackAll <- read.csv("data/jackAll.csv")
jackRainforest <- read.csv("data/jackRainforest.csv")
jackOpencountry <- read.csv("data/jackOpencountry.csv")
```


Getting data ready in a format for generalized linear modeling
```{r}
# All birds
modelDataAll <- vegPcaScores %>% 
  add_column (Site = vegData$Site_ID,
              Restoration.Type = as.factor(datSummary$Restoration.Type),
              jackknife = jackAll$jack1,
              nSpecies = jackAll$Species,
              totalDetections = datSummary$totalDetections,
              pointDetections = datSummary$pointDetections, 
              plantingYear = vegData$plantingYear) %>% 
  mutate ("roundjk" = round(jackknife))

# rainforest birds
modelData_rainForest <- vegPcaScores %>% 
  add_column (Site = vegData$Site_ID,
              Restoration.Type = as.factor(datSummary$Restoration.Type),
              jackknife = jackRainforest$jack1,
              nSpecies =  jackRainforest$Species,
              plantingYear = vegData$plantingYear) %>% 
  mutate ("roundjk" = round(jackknife))

# open country birds
modelData_openCountry <- vegPcaScores %>% 
  add_column (Site = vegData$Site_ID,
              Restoration.Type = as.factor(datSummary$Restoration.Type),
              jackknife = jackOpencountry$jack1,
              nSpecies =  jackOpencountry$Species,
              plantingYear = vegData$plantingYear) %>% 
  mutate ("roundjk" = round(jackknife))
```

Getting data ready for generalized linear mixed modeling
```{r}
# data for the GLMM
glmmAll <- richnessPerVisit[,-2] %>%
  full_join(modelDataAll, by = "Site")

# rainforest birds
glmmRainforest <- nDetectionsTrait %>%
  group_by(Site, Restoration.Type, Date) %>% 
  filter (Habitat == "RF") %>%
  summarise(richness = sum(forRichness)) %>%
  group_by(Site) %>% 
  mutate(visit = row_number()) %>%
  mutate(siteCode = str_extract(Site, pattern = "\\w+\\d+")) %>%
  mutate(siteCode = factor(siteCode)) %>%
  select(-Restoration.Type) %>%
  full_join(modelData_rainForest, by="Site")
  
# open-country birds
glmmOpencountry <- nDetectionsTrait %>%
  group_by(Site, Restoration.Type, Date) %>% 
  filter (Habitat == "OC") %>%
  summarise(richness = sum(forRichness)) %>%
  group_by(Site) %>% 
  mutate(visit = row_number()) %>%
  mutate(siteCode = str_extract(Site, pattern = "\\w+\\d+")) %>%
  mutate(siteCode = factor(siteCode)) %>%
  select(-Restoration.Type) %>%
  full_join(modelData_openCountry, by="Site")

# Let's look at species by foraging habit
# canopy birds
glmmCanopy <- nDetectionsTrait %>%
  group_by(Site, Restoration.Type, Date) %>% 
  filter (Habit == "CAN") %>%
  summarise(richness = sum(forRichness)) %>%
  group_by(Site) %>% 
  mutate(visit = row_number()) %>%
  mutate(siteCode = str_extract(Site, pattern = "\\w+\\d+")) %>%
  mutate(siteCode = factor(siteCode)) %>%
  select(-Restoration.Type) %>%
  full_join(modelDataAll, by="Site")
  
# ground-feeding birds
glmmGround <- nDetectionsTrait %>%
  group_by(Site, Restoration.Type, Date) %>% 
  filter (Habit == "GRD") %>%
  summarise(richness = sum(forRichness)) %>%
  group_by(Site) %>% 
  mutate(visit = row_number()) %>%
  mutate(siteCode = str_extract(Site, pattern = "\\w+\\d+")) %>%
  mutate(siteCode = factor(siteCode)) %>%
  select(-Restoration.Type) %>%
  full_join(modelDataAll, by="Site")

# mid-storey birds
glmmMidStorey <- nDetectionsTrait %>%
  group_by(Site, Restoration.Type, Date) %>% 
  filter (Habit == "MID") %>%
  summarise(richness = sum(forRichness)) %>%
  group_by(Site) %>% 
  mutate(visit = row_number()) %>%
  mutate(siteCode = str_extract(Site, pattern = "\\w+\\d+")) %>%
  mutate(siteCode = factor(siteCode)) %>%
  select(-Restoration.Type) %>%
  full_join(modelDataAll, by="Site")

# understorey birds
glmmUnderStory <- nDetectionsTrait %>%
  group_by(Site, Restoration.Type, Date) %>% 
  filter (Habit == "UND") %>%
  summarise(richness = sum(forRichness)) %>%
  group_by(Site) %>% 
  mutate(visit = row_number()) %>%
  mutate(siteCode = str_extract(Site, pattern = "\\w+\\d+")) %>%
  mutate(siteCode = factor(siteCode)) %>%
  select(-Restoration.Type) %>%
  full_join(modelDataAll, by="Site")

```


