---
editor_options: 
  chunk_output_type: console
---

## Indicator species analysis

This analysis aims to identify what species are “indicators” of groups of samples or treatment type. For instance: 

• A perfect indicator species will only occur in one group.
• Generalist species will occur across multiple groups and
therefore not a good indicator.
• Rare species are not sampled often, also not a good
indicator.
• Indicator values range from 0 to 1 but may also be
expressed as a percentage.
• Each species is assigned an indicator value for each
group and the significance of values can be assessed through permutations

For more information, visit this link: https://ichthyology.usm.edu/courses/multivariate/apr_11.pdf

Please note that when the aim is to determine which species can be used as indicators of certain site group, an approach commonly used in ecology is the Indicator Value [Dufrˆene and Legendre, 1997]. These authors defined an Indicator
Value (IndVal) index to measure the association between a species and a
site group. The method of Dufrˆene and Legendre [1997] calculates the IndVal index between the species and each site group and then looks for the
group corresponding to the highest association value. Finally, the statistical
significance of this relationship is tested using a permutation test.

Diagnostic (or indicator) species are an important tool in vegetation science, because these species can be used to characterize and indicate specific plant community types. A statistic commonly used to determine the association (also known
as fidelity, not to be confounded with the indicator value component) between species and vegetation types is Pearson’s phi coefficient of association
[Chytr´y et al., 2002]. This coefficient is a measure of the correlation between two binary vectors. The abundance-based counterpart of the phi coefficient is called the point biserial correlation coefficient (which is defined as "r.g")

See: https://cran.r-project.org/web/packages/indicspecies/vignettes/indicspeciesTutorial.pdf

```{r}
# Running the multi-pattern analysis across combinations of groups
# Note: supplementary code using the dataset on detections (see script 10_nmds_detections.rmd)
indicSpec <- multipatt(nmdsDat[, 3:ncol(nmdsDat)], nmdsDat$Restoration.type, func = "r.g", control = how(nperm=999))

# looking at associations with stratum/pairs of strata
summary(indicSpec)
```
